name: basearch
description: Flutter Sample Architecture Project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: 3.0.0
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dio: ^4.0.6
  google_maps_flutter: ^2.1.4
  shared_preferences: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

flutter:

  uses-material-design: true
  
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/

  fonts:
    - family: Lora
      fonts:
        - asset: lib/assets/fonts/Lora-Regular.ttf
        - asset: lib/assets/fonts/Lora-Bold.ttf
          weight: 400
        - asset: lib/assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic
    - family: Nunito
      fonts:
        - asset: lib/assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic


